[2024-10-25T23:00:41.923+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T23:00:41.942+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inserir_dados_mongodb.read_csv manual__2024-10-25T23:00:39.605539+00:00 [queued]>
[2024-10-25T23:00:41.952+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inserir_dados_mongodb.read_csv manual__2024-10-25T23:00:39.605539+00:00 [queued]>
[2024-10-25T23:00:41.953+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-25T23:00:41.978+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): read_csv> on 2024-10-25 23:00:39.605539+00:00
[2024-10-25T23:00:41.984+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-25T23:00:41.986+0000] {standard_task_runner.py:72} INFO - Started process 128 to run task
[2024-10-25T23:00:41.987+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'inserir_dados_mongodb', 'read_csv', 'manual__2024-10-25T23:00:39.605539+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag_save_mongodb_v3.py', '--cfg-path', '/tmp/tmp0pbpmvej']
[2024-10-25T23:00:41.991+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask read_csv
[2024-10-25T23:00:42.048+0000] {task_command.py:467} INFO - Running <TaskInstance: inserir_dados_mongodb.read_csv manual__2024-10-25T23:00:39.605539+00:00 [running]> on host 9e883d86a6d2
[2024-10-25T23:00:42.149+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='inserir_dados_mongodb' AIRFLOW_CTX_TASK_ID='read_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T23:00:39.605539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T23:00:39.605539+00:00'
[2024-10-25T23:00:42.150+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T23:00:42.194+0000] {logging_mixin.py:190} INFO - Dados lidos com sucesso!
[2024-10-25T23:00:42.194+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T23:00:42.205+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T23:00:42.206+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=inserir_dados_mongodb, task_id=read_csv, run_id=manual__2024-10-25T23:00:39.605539+00:00, execution_date=20241025T230039, start_date=20241025T230041, end_date=20241025T230042
[2024-10-25T23:00:42.243+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T23:00:42.273+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-25T23:00:42.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
